### ISSUE TITLE
player can get stuck between camp and static collider if they place it too close while standing between placement and collider.

### ISSUE THREAD

**Issue by loteque** [loteque/GoblinGame#178]
https://github.com/loteque/GoblinGame/assets/23508546/f430cc21-8879-4085-875f-0a20eabb0398

**Comment by jonathandavidlewis** [comment]
https://github.com/loteque/GoblinGame/assets/23508546/709d8d92-a910-4215-8944-e5f6f3b898b2

**Comment by jonathandavidlewis** [comment]
This bug as described is solved with the change of the marker position distance. You can't place anything right next to yourself.

How about if you press the base placement button once, you see where it will go, then if you press it again, it gets placed?

This would let the player more clearly see where it will go.

It will also open up the possibility to more clearly indicate to the player whether or not where they are going to try to put the base is a valid position (not colliding with anything)

**Comment by loteque** [comment]
That is an enhancement but it is so good I think if it can be done quickly we should get it in there. ONLY if it is quick and I mean QUICK.

**Comment by jonathandavidlewis** [comment]
That's not blocking for the issue, just checking.
