### ISSUE TITLE
follwing goblins are not entering idle when player is outside their detection radius.

### ISSUE THREAD

**Issue by loteque** [loteque/GoblinGame#183]

**Comment by jonathandavidlewis** [comment]
@loteque I'm unable to reproduce this. This is the behavior I see, actor entering idle state.

https://github.com/loteque/GoblinGame/assets/23508546/df3999d1-abfc-4c57-a8b7-29f8c622402f

**Comment by loteque** [comment]
As far as I remember there is a radius an actor must be within in order to become a follower. We will call this `The Radius`
The actors speed property makes them slower than the player.
When the actor falls behind enough for the player to be outside `The Radius` --
that is to say: Actor::_on_body_exited, if body, if in group, Player -- the actor should enter the idle state and no longer follow the player.

**Comment by jonathandavidlewis** [comment]
@loteque Ah, I get it. Ty
