### ISSUE TITLE
Tests scenes broken due to dependancy on tut_conn

### ISSUE THREAD

**Issue by jonathandavidlewis** [loteque/GoblinGame#186]
![image](https://github.com/loteque/GoblinGame/assets/23508546/336031c3-e3e1-4fa5-b4e0-66e3614a28d0)

**Comment by loteque** [comment]
Maybe this helps? Perhaps Godot is resetting values again?
![image](https://github.com/loteque/GoblinGame/assets/69282314/56c93605-9eaf-41bf-baac-d09b5277183e)

**Comment by jonathandavidlewis** [comment]
_ready requires tut_con to be connected for the player character to load, so it means it has a new external dependency not in the test scenes and for any future test scene to setup.

**Comment by loteque** [comment]
> _ready requires tut_con to be connected for the player character to load, so it means it has a new external dependency not in the test scenes and for any future test scene to setup.

Ah, I see. I didn't like that bit of code anyway. I can fix that next. You can assign this to me.
