### ISSUE TITLE
Add dialog in tutorial scene

### ISSUE THREAD

**Issue by jonathandavidlewis** [loteque/GoblinGame#219]
- [ ] Dialog box pops up. on bottom left

- [ ] Dialog box should be translucent
- [ ] Character portrait:
  - [ ] Left side
  - [ ] Opaque
  - [ ] Top of head is above top of dialog frame
  - [ ] Should not block other inputs
  - [ ] player presses "menu" to continue
  
- [ ] Text translucent (Try 70%)

Keep dialog terse.

If there is a quest / task, add it to the message queue.

### Introductory Dialogue

*Grizzle:* "Well, look who finally showed up! The runt of the litter! Don’t worry, we’ll whip you into shape in no time."

*Snark:* "Well, maybe... If they don't trip over their own feet first! Honestly, Grizzle, do we really have to babysit this one?"

*Grizzle:* "Now, now, Snark. Everyone starts somewhere. Even this... uh... _unique_ individual deserves a chance."

*Snark:* "Fine. But if they mess up, it’s on you. Now, let’s get this over with."

*Grizzle:* "Alright, runt. We’ve got a lot to cover. Pay attention and maybe, just maybe, you’ll survive. We’re in a bit of a pickle. Corrupted goblins are spreading like mold on old cheese. It’s your job to clean them up. Let’s start with the basics."

---

### Learning the Basics

**Inspiring Goblins:**

*Grizzle:* "See those goblins lazing around? They need some inspiration. Inspire them! They’ll follow you if you can muster some enthusiasm."

*Snark:* "Enthusiasm? This one? Hah! Just try not to bore them to death, runt."

#### Event trigger: Goblin stops following.

*Grizzle:* "They’re falling behind. Looks like they need some more inspiration! Keep them on their toes!"

*Snark:* "Yeah, if you can muster the courage. Don't let them fall out of line, runt!"

"They seem to be dragging their feet. Give 'em another pep talk with ‘shift’. Speed ‘em up! Don't forget to keep inspiring them, or they might just start napping again."

---

### Building and Collecting

**Throwing Goblins:**

*Grizzle:* "Now for the fun part! Throw your goblins! Aim for that scrap pile over there. It's like goblin bowling! "

*Snark:* "Try not to get a gutter ball!... Think you can handle that without throwing out your back, runt?"

### Event: goblins collect scrap:

*Grizzle:* "Look, they're even collecting scrap! Well, you need some place to put all that shiny scrap."

*Snark:* "A base. You need a base. Don't hurt yourself. "

*Grizzle:* "Build a base and the goblins will keep the scrap comin in!"

### Event: Player builds base

Player Character: "This base isn't just a place to store scrap. It's a foundation for our community to grow and thrive."

*Grizzle:* "Oh, you made us proud!"

*Snark:* "Let's just say you're less of an embarrassment"

### Event: On Goblin return scrap:
*Grizzle:* "And don't worry if they grumble. Goblins love a bit of grunt work!"
*Snark:* "Hey, I don't see you doing any work, ya lazy dog!"
*Player Character:* "Great work everyone! We can do this is we work together!"

---

#### Event: Goblin starts training

Grizzle: "Look at that! You’ve collected enough scrap. Now our base can start training new goblins."

Snark: "Finally! Some reinforcements. Let’s hope SOME GOBLIN knows what they're doing!"

Player Character: "Every new goblin is a new opportunity. Let's welcome them and help them grow."

---

### Combat Training

**Fighting Corrupted Goblins:**

### Event: Corrupted goblin on screen:

*Grizzle:* "Look! Corrupted goblins! Show them what you’ve got by throwing our goblins at them."

*Snark:* "Try not to flinch, runt. They can smell fear. And incompetence."

### Event: Corrupted goblin dies:

*Snark:* "You did it! Maybe I was wrong about you... Bwahahaha! I'm kidding, ya mutt! My belly button coulda taken out that corrupted goblin!"

*Snark:* "Don't listen to him. He's just cranky"

Player Character: "Great job, everyone! Together, we will turn the tide! We must press on!"

---

**Finding the Enemy Base:**

*Grizzle:* "Now, scout ahead and find their base. Lead your inspired goblins to victory!"

*Snark:* "And if you get lost, don't let me catch you crying!"

---

**Destroying the Enemy Base:**

### Event: Enemy base renders on screen

*Grizzle:* "There it is! Bring down the enemy base by throwing our goblins at it. You’ve got this!"

*Snark:* "Just aim properly. We don’t need goblins stuck in the ceiling again."

Player Character: "This is our moment. Let's work together and bring down that base!"

---

#### Event: Enemy goblin base destroyed

*Grizzle:* "Not bad, runt! You might just make survive down here. Keep this up, and we might even start to respect you!"

*Snark:* "Respect? Let’s not get ahead of ourselves. But yeah, you did okay. For a runt."

*Grizzle:* "Cheer up, Snark. Everyone loves an underdog story. Now, go out there and show those corrupted goblins who's boss!"

*Player Character:* "Great work, everyone! We've taken back this land and we can do the same again and again until our homeland is free from corruption!

END TUTORIAL

**Comment by loteque** [comment]
[ ] level stutters when the dialogic timeline starts to play
[ ] add button notification when goblins fall behind
