### ISSUE TITLE
actor ghost animation should be instantiead on died() call

### ISSUE THREAD

**Issue by loteque** [loteque/GoblinGame#241]
instantiate the ghost animation parented to the level to that the actor process may be stopped. it doesn't need to be a node that exists in the tree. the packed scene file could be referenced in the actor object or something like that.

![image](https://github.com/loteque/GoblinGame/assets/69282314/032b1ae3-6d27-428e-ac66-316071adf30a)

**Comment by loteque** [comment]
This sldo needs to be done for the player character

**Comment by loteque** [comment]
@jonathandavidlewis, I think I suggested a change here but upon further review, I think the way we are currently doing this with the ghost scene as a scene node in the actor/player scene that gets parented to the acotor/players parent level node; It looks like it is working just fine. I currently don't really see a need to change this. Do you agree?

**Comment by jonathandavidlewis** [comment]
Its not a priority. not necessary. I'm satisfied either way.
