### ISSUE TITLE
Player explores the map.

### ISSUE THREAD

**Issue by jonathandavidlewis** [loteque/GoblinGame#31]
- [x] Bigger map: about 4 screens x 4 screens (small map)
- [x] camera follows player character

**Comment by loteque** [comment]
New Map size:

![Image](https://github.com/loteque/GoblinGame/assets/69282314/92097ef2-75a9-4205-a0fc-c40f1ef42207)

**Comment by loteque** [comment]
camera follows player (keep in mind the map is much bigger than what is explored in this video.)




https://github.com/loteque/GoblinGame/assets/69282314/3bd40acc-f7a6-4fb2-b917-413316cdb682
