### ISSUE TITLE
Player locates and collects goblins.

### ISSUE THREAD

**Issue by jonathandavidlewis** [loteque/GoblinGame#32]
- [ ] add multiple goblins placed around the map that player can collect
  - [x] depends on #31 
  - [ ] multiple goblins
    - [ ] actors need obstacle avoidance
  - [ ] place goblins around the map

**Comment by loteque** [comment]
I think we need obstacle avoidance for the goblins, lol


https://github.com/loteque/GoblinGame/assets/69282314/a1721860-ee7e-4e13-9a63-d28f15d5ad5e

**Comment by loteque** [comment]
https://github.com/loteque/GoblinGame/assets/69282314/721f4475-8369-44e6-a2dd-5c7688813eaa
