### ISSUE TITLE
Player finds a corrupted goblin.

### ISSUE THREAD

**Issue by jonathandavidlewis** [loteque/GoblinGame#33]
NPC goblins and enemy goblins should be able to inherit the same scene.
- [x] Create a Corrupted Goblin and place on map
  - [x] Enemy Goblins should be in an Enemy Group
  - [x] Enemy goblins should be visually distinct to the NPC goblins

**Comment by loteque** [comment]
closed by 91bfb0fc46a957e639def548d44e06cfb2d089f7
