### ISSUE TITLE
When x, collect scrap

### ISSUE THREAD

**Issue by jonathandavidlewis** [loteque/GoblinGame#99]
How does scrap get collected?

The player clicks on a scrap pile?
Then, they automatically collect 1 scrap every second until the pile is empty?

**Comment by loteque** [comment]
Both enemy and NPC can collect scrap: enemy and NPC share a script.

- When an NPC is close to scrap their nav-agent will direct them towards it.
- When navigation is finished NPC will stand in one place for small amount of time
- When timer is over 1 unit of scrap will be added to NPC inventory (inv_max = 1 for now)
- scrap pile inv is decremented by 1
- when scrap pile inventory is 0 it id queue free.
- Player collects NPC
- When Player collects NPC they move to the base with NPC
- When NPC is Close to Base Scrap is added to base upgrade meter
- When base upgrade meter is increased scrap is removed from the NPCs inventory

**Comment by jonathandavidlewis** [comment]
@loteque Thanks!
